### ISSUE TITLE
Sample to send dmx command

### ISSUE THREAD

**Issue by iiidmaxer** [MichaelJames6/ArtNet.Net#2]
Hi There,

Would you be able to provide an example of how to send a command to a DMX device?  I checked "http://acn.codeplex.com/SourceControl/latest" and looked at the StreamingAcn Sample for some ideas - but no joy there.

-Bob

**Comment by MikeCodesDotNET** [comment]
Hey, 

I've only just seen this so sorry for the huge delay in response. 

There is actually code within the solution that shows how to output some DMX values. Did you have any luck using it? I've tested locally using Capture Sweden's visualiser and it appears to work. 

Cheers,
Mike J
